#!/bin/bash

cd $1 && ( [ -f ../cert.pem ] && [ -f ../key.pem ] || openssl req -x509 -newkey rsa:2048 -nodes -keyout ../key.pem -out ../cert.pem -days 365 -subj "/CN=localhost" ) && python3 -c "import http.server,ssl;s=http.server.ThreadingHTTPServer(('0.0.0.0',8443),http.server.SimpleHTTPRequestHandler);c=ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER);c.load_cert_chain('../cert.pem','../key.pem');s.socket=c.wrap_socket(s.socket,server_side=True);print('Serving HTTPS on 0.0.0.0:8443');s.serve_forever()"
